name: Build and Push to ECR
on:
  workflow_dispatch:

env: 
  AWS_REGION: "us-west-2"
  APP_ID: "football-tracker"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2   

      - name: Build and push to ECR
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: |
            ${{ secrets.ECR_HUB }}/${{ env.APP_ID }}:latest            
          file: build/Dockerfile
